# Generated by Django 5.0.7 on 2024-07-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_course_alter_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular User (Freshman)'), ('parent', 'Parent (Orientation Lead)'), ('admin', 'Admin (G9)')], default='regular', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
