# Generated by Django 5.0.7 on 2024-07-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='event_videos/')),
            ],
        ),
    ]
