# Generated by Django 5.0.7 on 2024-07-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orientation',
            name='date',
        ),
        migrations.AlterField(
            model_name='orientation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/'),
        ),
    ]
